const SHOP_DATA = [
	{
		title: 'Women',
		items: [
			{
				id: 23,
				name: 'Blue Tanktop',
				description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequatur atque quod voluptas dignissimos inventore illo omnis suscipit placeat fugit repudiandae similique sit, aperiam corporis modi asperiores debitis officia consequuntur enim.',
				imageUrl: 'https://i.ibb.co/7CQVJNm/blue-tank.png',
				price: 25,
				category: 'Women',
				rating: 4.1,
				size: ['XS', 'S', 'M', 'L', 'XL'],
			},
			{
				id: 24,
				name: 'Floral Blouse',
				description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequatur atque quod voluptas dignissimos inventore illo omnis suscipit placeat.',
				imageUrl: 'https://i.ibb.co/4W2DGKm/floral-blouse.png',
				price: 20,
				category: 'Women',
				rating: 3.6,
				size: ['XS', 'S', 'M'],
			},
			{
				id: 25,
				name: 'Floral Dress',
				description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequatur atque quod voluptas dignissimos inventore illo omnis suscipit placeat fugit repudiandae similique sit, aperiam corporis modi asperiores debitis officia consequuntur enim.',
				imageUrl: 'https://i.ibb.co/KV18Ysr/floral-skirt.png',
				price: 80,
				category: 'Women',
				size: ['L', 'XL'],
			},
			{
				id: 26,
				name: 'Red Dots Dress',
				description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequatur atque quod voluptas dignissimos inventore illo omnis suscipit placeat aperiam corporis modi asperiores debitis officia consequuntur enim.',
				imageUrl: 'https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png',
				price: 80,
				category: 'Women',
				rating: 4.2,
				size: ['XS', 'S', 'M', 'XL'],
			},
			{
				id: 27,
				name: 'Striped Sweater',
				description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequatur atque quod voluptas dignissimos inventore illo omnis suscipit placeat fugit repudiandae similique sit, aperiam corporis modi asperiores debitis officia consequuntur enim.',
				imageUrl: 'https://i.ibb.co/KmSkMbH/striped-sweater.png',
				price: 45,
				category: 'Women',
				rating: 4.7,
				size: ['XS', 'L', 'XL'],
			},
			{
				id: 28,
				name: 'Yellow Track Suit',
				description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aperiam corporis modi asperiores debitis officia consequuntur enim.',
				imageUrl: 'https://i.ibb.co/v1cvwNf/yellow-track-suit.png',
				price: 135,
				category: 'Women',
				rating: 2.5,
				size: ['XS', 'S', 'M', 'L'],
			},
			{
				id: 29,
				name: 'White Blouse',
				description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequatur atque quod voluptas dignissimos inventore illo omnis suscipit placeat fugit repudiandae similique sit.',
				imageUrl: 'https://i.ibb.co/qBcrsJg/white-vest.png',
				price: 20,
				category: 'Women',
				rating: 3,
				size: ['XS', 'S', 'M'],
			},
		],
	},
	{
		title: 'Men',
		items: [
			{
				id: 30,
				name: 'Camo Down Vest',
				description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequatur atque quod voluptas dignissimos inventore illo omnis suscipit placeat fugit repudiandae similique sit, aperiam corporis modi asperiores debitis officia consequuntur enim.',
				imageUrl: 'https://i.ibb.co/xJS0T3Y/camo-vest.png',
				price: 325,
				category: 'Men',
				rating: 4.7,
				size: ['S', 'M', 'L', 'XL', 'XXL'],
			},
			{
				id: 31,
				name: 'Floral T-shirt',
				description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequatur atque quod voluptas dignissimos aperiam corporis modi asperiores debitis officia consequuntur enim.',
				imageUrl: 'https://i.ibb.co/qMQ75QZ/floral-shirt.png',
				price: 20,
				category: 'Men',
				rating: 3.2,
				size: ['S', 'M', 'XXL'],
			},
			{
				id: 32,
				name: 'Black & White Longsleeve',
				description: 'Consequatur atque quod voluptas dignissimos inventore illo omnis suscipit placeat fugit repudiandae similique sit, aperiam corporis modi asperiores debitis officia consequuntur enim.',
				imageUrl: 'https://i.ibb.co/55z32tw/long-sleeve.png',
				price: 25,
				category: 'Men',
				rating: 5,
				size: ['XL', 'XXL'],
			},
			{
				id: 33,
				name: 'Pink T-shirt',
				description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.',
				imageUrl: 'https://i.ibb.co/RvwnBL8/pink-shirt.png',
				price: 25,
				category: 'Men',
				rating: 1.7,
				size: ['S', 'M', 'XL', 'XXL'],
			},
			{
				id: 34,
				name: 'Jean Long Sleeve',
				description: 'Aperiam corporis modi asperiores debitis officia consequuntur enim.',
				imageUrl: 'https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png',
				price: 40,
				category: 'Men',
				rating: 3.3,
				size: ['M', 'L', 'XL', 'XXL'],
			},
			{
				id: 35,
				name: 'Burgundy T-shirt',
				description: 'Atque quod voluptas dignissimos inventore illo omnis suscipit placeat fugit repudiandae similique sit, aperiam corporis modi asperiores debitis officia consequuntur enim.',
				imageUrl: 'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
				price: 25,
				category: 'Men',
				rating: 4.7,
				size: ['L', 'XL', 'XXL'],
			},
		],
	},
	{
		title: 'Featured',
		items: [
			{
				id: 36,
				name: 'Adidas NMD',
				description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequatur atque quod voluptas dignissimos inventore illo omnis suscipit placeat fugit repudiandae similique sit, aperiam corporis modi asperiores debitis officia consequuntur enim.',
				imageUrl: 'https://i.ibb.co/0s3pdnc/adidas-nmd.png',
				price: 220,
				category: 'Men',
				rating: 4.7,
				size: ['7', '8', '9', '10', '11'],
			},
			{
				id: 37,
				name: 'Blue Beanie',
				description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequatur atque quod voluptas dignissimos inventore illo omnis suscipit placeat fugit repudiandae similique sit.',
				imageUrl: 'https://i.ibb.co/ypkgK0X/blue-beanie.png',
				price: 18,
				category: 'Men',
				rating: 3.7,
				size: ['One size'],
			},
			{
				id: 38,
				name: 'Black Converse',
				description: 'Consequatur atque quod voluptas dignissimos inventore illo omnis suscipit placeat fugit repudiandae similique sit, aperiam corporis modi asperiores debitis officia consequuntur enim.',
				imageUrl: 'https://i.ibb.co/bPmVXyP/black-converse.png',
				price: 110,
				category: 'Unisex',
				rating: 4.7,
				size: ['5', '6', '7', '8', '9', '10', '11'],
			},
			{
				id: 39,
				name: 'Air Jordan Limited',
				description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.',
				imageUrl: 'https://i.ibb.co/w4k6Ws9/nike-funky.png',
				price: 190,
				category: 'Unisex',
				rating: 2.7,
				size: ['5', '6', '7', '10', '11'],
			},
			{
				id: 40,
				name: 'Floral Blouse',
				description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequatur atque quod voluptas dignissimos inventore illo omnis suscipit placeat fugit repudiandae similique sit, aperiam corporis modi asperiores debitis officia consequuntur enim.',
				imageUrl: 'https://i.ibb.co/4W2DGKm/floral-blouse.png',
				price: 20,
				category: 'Women',
				rating: 3.6,
				size: ['XS', 'S', 'M', 'L'],
			},
		],
	},
];

export default SHOP_DATA;
